GENRES = {
    "Aksiyon": "Action",
    "Macera": "Adventure",
    "Animasyon": "Animation",
    "Biyografi": "Biography",
    "Komedi": "Comedy",
    "Suç": "Crime",
    "Belgesel": "Documentary",
    "Drama": "Drama",
    "Aile": "Family",
    "Fantastik": "Fantasy",
    "Kara Film": "Film-Noir",
    "Tarih": "History",
    "Korku": "Horror",
    "Müzik": "Music",
    "Müzikal": "Musical",
    "Gizem": "Mystery",
    "Romantik": "Romance",
    "Bilim kurgu": "Sci-Fi",
    "Kısa Film": "Short",
    "Spor": "Sport",
    "Gerilim": "Thriller",
    "Savaş": "War",
    "Batı": "Western"
}
